### ISSUE TITLE
Замечания по lw1

### ISSUE THREAD

**Issue by lulldev** [JohnSmithW/lab1#1]
```css
get-some{
  display:none;
  font-size:  1px;
  max-height: 0px;
  max-width: 0px; 
  opacity: 0; 
  overflow: hidden; 
  font-family: sans-serif;
}
```

- get-some - класс, а не тег
- поправить форматирование `{`
- get-some - имя класса - ни о чем не говорит

ее лучше выпилить:
```html
    <div class="get-some">
     &zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;
    </div>
```

**Comment by lulldev** [comment]
форматирование не соответствует соглашению (2 spaces)

**Comment by lulldev** [comment]
```html
<td class="bg_white">
 <table class="table-1" role="presentation">
```

в коде смешиваются kebab и underscore стили именования

**Comment by lulldev** [comment]
классы форматируются отдельно друг от друга. не стоит соединять их 

<img width="396" alt="Screen Shot 2019-09-13 at 16 13 24" src="https://user-images.githubusercontent.com/15219574/64865178-6f4c4b00-d641-11e9-8131-351f624da5a8.png">

**Comment by lulldev** [comment]
```css
.table-1{
  border:0; 
  padding:0; 
  border-spacing:0; 
  width:100;
}
.tr-1{
  border-bottom: 1px solid rgba(0,0,0,.05);
}
```

после свойства css нужно поставить `:`
